/**
 * Swagger UI over the two specs this repo publishes, bundled from `node_modules`
 * — no CDN, so the docs work offline and the rendered contract is exactly the
 * one this build generated its types from.
 *
 * - **Platform API** (`web/openapi.yaml`) — generated by the server build
 *   (`cmd/openapi`); `/privacy/v1` + `/iam/v1`.
 * - **Auth API** (`web/openapi-auth.yaml`) — hand-curated; the full Supabase
 *   Auth-compatible surface `internal/auth` actually serves at `/auth/v1`
 *   (email/phone/PKCE/external OAuth/MFA/passkeys/SSO-SAML/OAuth2 server).
 */
import { useEffect, useRef, useState } from 'react'
import SwaggerUIBundle, { type SwaggerRequest } from 'swagger-ui-dist/swagger-ui-bundle.js'
import 'swagger-ui-dist/swagger-ui.css'
// `?url` hands Vite the YAML as an asset URL; swagger-ui parses YAML itself, so
// the app never needs a YAML parser of its own.
import specUrl from '../../openapi.yaml?url'
import authSpecUrl from '../../openapi-auth.yaml?url'
import { hasServiceToken } from '../api/client'
import { resolveManagementToken, useCredentialMode } from '../lib/credentialMode'

/**
 * The spec's only server. Try-it-out would fire cross-origin at it and be
 * blocked (Dilion configures no CORS on purpose), so every request is rewritten
 * onto this app's own origin and goes through the Vite proxy instead.
 */
const SPEC_ORIGIN = 'http://localhost:8787'

type SpecId = 'platform' | 'auth'

const SPECS: readonly {
  id: SpecId
  label: string
  url: string
  /** Shown next to the heading; kept in sync with the spec by hand. */
  summary: string
}[] = [
  {
    id: 'platform',
    label: 'Platform API',
    url: specUrl,
    summary: 'OpenAPI 3.1 · 30 operations · generated',
  },
  {
    id: 'auth',
    label: 'Auth API (Supabase compatible)',
    url: authSpecUrl,
    summary: 'OpenAPI 3.1 · 69 operations · hand-curated',
  },
]

async function requestInterceptor(request: SwaggerRequest): Promise<SwaggerRequest> {
  if (request.url.startsWith(SPEC_ORIGIN)) {
    request.url = request.url.slice(SPEC_ORIGIN.length) || '/'
  }
  // Only fill in what the operator did not: an explicit Authorize in the UI
  // (or a `dk_` key typed into it) must win over the ambient credential, which
  // is whichever one the console's selector currently points at.
  const headers = request.headers ?? {}
  const hasAuth = Object.keys(headers).some((name) => name.toLowerCase() === 'authorization')
  if (!hasAuth) {
    const token = await resolveManagementToken()
    if (token) headers.Authorization = `Bearer ${token}`
  }
  request.headers = headers
  return request
}

export function DocsPage() {
  const containerRef = useRef<HTMLDivElement>(null)
  const [specId, setSpecId] = useState<SpecId>('platform')
  const mode = useCredentialMode()
  const spec = SPECS.find((s) => s.id === specId) ?? SPECS[0]

  useEffect(() => {
    const node = containerRef.current
    if (!node) return
    SwaggerUIBundle({
      domNode: node,
      url: spec.url,
      presets: [SwaggerUIBundle.presets.apis],
      // This app owns `window.location.hash` for its own router; letting
      // swagger-ui write operation ids into it would navigate away from #/docs.
      deepLinking: false,
      docExpansion: 'list',
      defaultModelsExpandDepth: 1,
      tryItOutEnabled: true,
      requestInterceptor,
    })
    return () => {
      node.replaceChildren()
    }
    // Re-initializing on every spec change is deliberate: swagger-ui has no
    // supported way to swap `url` on a live instance, and the teardown above
    // empties the host node first.
  }, [spec.url])

  return (
    <>
      <section className="card">
        <div className="card-head">
          <h2>API Docs</h2>
          <span className="muted small">{spec.summary}</span>
        </div>
        <label className="select docs-spec-select">
          Spec
          <select value={specId} onChange={(e) => setSpecId(e.target.value as SpecId)}>
            {SPECS.map((s) => (
              <option key={s.id} value={s.id}>
                {s.label}
              </option>
            ))}
          </select>
        </label>
        <div
          className={`dev-banner ${hasServiceToken || mode === 'SESSION' ? '' : 'dev-banner-missing'}`}
        >
          <span className="dev-banner-tag">DEV ONLY</span>
          {hasServiceToken || mode === 'SESSION' ? (
            <p>
              <strong>Try it out</strong> is wired up: the spec declares{' '}
              <code>{SPEC_ORIGIN}</code>, but a <code>requestInterceptor</code> rewrites every call
              onto this page&rsquo;s own origin so it travels the Vite proxy (no CORS), and injects
              an <code>Authorization</code> header whenever the request carries none of its own. The
              injected credential follows the <strong>관리 API 자격증명</strong> selector in the
              Admin console — currently <code>{mode}</code>, i.e.{' '}
              {mode === 'SERVICE' ? (
                <>
                  the dev <code>VITE_DILION_SERVICE_TOKEN</code>, a full-tenant credential that
                  bypasses RBAC
                </>
              ) : (
                <>the signed-in user&rsquo;s access token, authorized by RBAC (401 when signed out)</>
              )}
              . An explicit <em>Authorize</em> here still wins over it.{' '}
              <strong>Every call you fire really mutates the dev tenant</strong>, and a real service
              must never ship a service token to a browser.
            </p>
          ) : (
            <p>
              <code>VITE_DILION_SERVICE_TOKEN</code> is not set, so requests are still proxied to
              the Dilion server but sent unauthenticated — expect{' '}
              <code>401 unauthenticated</code>. Add the token to <code>web/.env.local</code> and
              restart <code>npm run dev</code>.
            </p>
          )}
          {specId === 'auth' && (
            <p>
              On the <strong>Auth API</strong> the injected service token is the wrong credential
              for the self-service endpoints: <code>GET/PUT /auth/v1/user</code> and{' '}
              <code>POST /auth/v1/logout</code> want a <strong>user access token</strong> — press{' '}
              <em>Authorize</em> and paste one (My account → Session tools prints the current
              session&rsquo;s, or just run <code>POST /auth/v1/signup</code> here and copy its{' '}
              <code>access_token</code>). Public endpoints (<code>/signup</code>,{' '}
              <code>/token</code>, <code>/health</code>, <code>/.well-known/*</code>,{' '}
              <code>/verify</code>, <code>/otp</code>, passkey authentication) need no credential;{' '}
              <code>/auth/v1/admin/*</code> takes the <code>service_role</code> JWT (or a user
              token whose actor holds <code>users.admin</code>); <code>/oauth/token</code>{' '}
              authenticates the <strong>OAuth client</strong> itself (basic/post/none). Several
              groups are feature-flag gated and answer 404 until enabled —{' '}
              <code>DILION_AUTH_PASSKEY_ENABLED</code>, <code>_OAUTH_SERVER_ENABLED</code>,{' '}
              <code>_SAML_ENABLED</code>, <code>_EXTERNAL_PHONE_ENABLED</code>.
            </p>
          )}
        </div>
      </section>

      <section className="card swagger-card">
        <div ref={containerRef} className="swagger-host" />
      </section>
    </>
  )
}
